baseURL = "http://example.org/"
languageCode = "en-us"
title = "JakeVC"
disqusShortname = "jakevc"
paginate = 3

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Jake VanCampen"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"

[params]
    customCss = ["scss/main.scss"]
    dateformShort = "Jan 2, 2006"
    homeSubtitle = "Writing about my current interests"

 # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/jake_vancampen"

  [[params.social]]
    name = "email"
    url  = "mailto:jake.vancampen7@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/jakevc"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/jakevancampen/"