baseurl = "/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Jake VanCampen"
title = "jakevc"
disqusshortname = "jakevc"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Jake's blog"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
share = false
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
share_on_googleplus = false
latestpostcount = 5
github = "jakevc"
email = "jake.vancampen7@gmail.com"
linkedin = "jakevancampen"
twitter = "jake_vancampen"
instagram = "vancampman"
usesmallsummarycard = true 
posts_navigation = true
githubRepo = "jakevc/jakevc/tree/master"
small_banner_logo = true 

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
