baseurl = "/"
languageCode = "en"
title = "Jake VanCampen"
# copyright = "&copy; <a href=\"https://github.com/ribice\"></a> 2017"
disqusShortname = "jakevc"
theme = "kiss"
relaltiveurls=true
connonifyurls=false

# Number of posts per page
Paginate = 5
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]


[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = false # Adds powered by Hugo dd Kiss below Copyright section
related = true # Includes related articles

# social features
[params.social]
twitter = "jake_vancampen"
github = "jakevc"
email = "jake.vancampen7@gmail.com"
linkedin = "jakevancampen"

# about
[params.sections_left]
"/bio" = "Bio"
"/cv" = "CV"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

