---
title: "Curriculum Vitae"
author: "Jake VanCampen"
date: "7/1/2018"
output: html_document
---

# Education

MS Bioinformatics and Genomics | University of Oregon | Expected Dec. 2018

BS Biochemistry, ACS Certified | University of Portland | May 2017


# Skills

Languages: `Python` `R` `bash` `go` `git` `Stan`


# Work Experience 

**Graduate Researcher (Genomics) - Stowers Institute for Medical Research - (04/2018-current)**

  - Perform Bioinformatic analyses in the Computational Biology/Genomics department.
  - Utilize workflow management (snakemake) and version control (git) for maximal reproducibility, and reusability of computational pipelines. 
  
  
**Chemistry Workshop Leader - University of Portland - (01/2015 - 04/2017)**

  - Taught a weekly chemistry workshop to help general chemistry students learn core concepts.
  - Graded homework, and held weekly office hours for one-on-one tutoring.
  

**Chemistry Research Assistant - Univeristy of Portland - (05/2017 - 12/2016)**

  - Optimized a gel-electrophoresis assay to determine hyaluronidase inhibition of plant extract polyphenols. 
  - Determined novel plant-extract inhibitors with implications for neurodegenerative repair.
  - Presented work at professional conferences.
  
  
**Bicycle Mechanic - University of Portland - (10/2013 - 04/2017)**

  - Performed new bike builds, routine repairs, and complex overhauls.
  - Managed shop inventory for weekly parts orders.

  
# CONFERENCES AND PRESENTATIONS

> VanCampen J., Norris B., Claridge S.E., Simons N.D., Ting N., Eick G., Sterner K.N. De novo
miRNA prediction in the Ugandan red colobus genome reveals miRNAs unique to SIV
non-progressors. Genomics in Action, University of Oregon, 2018.

> Technical Session Assistant at the ACS Green Chemistry conference. Portland, OR. July
2016.

> VanCampen J., Rodriguez M. 2016. Spectroscopic investigation
of HCl and DCl gas: vibrational dynamics and isotopic comparison. University of Portland
undergraduate poster session. April, 2016.

> VanCampen J., Hoffman A. 2015. Anti-hyaluronidase activity of various methanolic plant
extracts and implications in neurodegenerative repair. Poster # CHED 1132

> American Chemical Society National Meeting. San Diego, CA. March 2016.
VanCampen J., Hoffman A. Anti-hyaluronidase activity of various methanolic plant
extracts, and implications in neurodegenerative repair. Presented at the M.
  



